### PR TITLE
Update stringify-error.js

### PR DESCRIPTION
**Pull request by mheiber**
Make the language gender-neutral

### CODE REVIEW

**Comment by jfhbrook** [comment]
Interesting.

I'm all for gender-neutral language when appropriate, but me/myself is definitely male.

**Comment by jfhbrook** [comment]
Though, you did remind me to fix that message since I changed my username...

**Comment by jfhbrook** [comment]
Fixed in https://github.com/jfhbrook/browserify-cdn/commit/c8b98da751cdc958ab94f374b038044b492b48ff

**Comment by mheiber** [comment]
Haha. I was referring to "Include the ENTIRETY of the contents of this
message, and he can try to help you out.''

**Pull request closed without merging**
